CREATE TABLE people (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(150) NOT NULL,
  second_name VARCHAR(100) NOT NULL,
  date_of_birth DATETIME NOT NULL,
  profession VARCHAR(100) NOT NULL,
  salary DECIMAL(10,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;